name: TGVNKeepInventoryRune
version: ${project.version}
main: vn.vinhgaming.tgvnkeepinventoryrune.TGVNKeepInventoryRune
api-version: 1.13
commands:
  keepinventoryrune:
    description: Main command
    aliases:
      - kir
    usage: /<command> [give/removeprotection/reload]